stages:
  convert-parflux-output:
    cmd: nice duckdb < 01_convert.sql
    deps:
    - 01_convert.sql
    - data/pyric/reg.udral.physics.electricity.SourceTs.0.1.parquet
    - data/pyric/reg.udral.service.battery.Status.0.2.parquet
    - data/pyric/starcopter.aeric.bms.SystemStatus.0.4.parquet
    - data/pyric/starcopter.aeric.bms.Temperatures.0.1.parquet
    - data/sm15k/supply.parquet
    outs:
    - data/packs.parquet
    - data/sm15k.parquet
  parse-cycles:
    cmd: python 02_parse_cycles.py
    deps:
    - 02_parse_cycles.py
    - data/sm15k.parquet
    outs:
    - data/cycles.csv:
        cache: false
    - data/cycles.parquet
